from pathlib import Path

path = Path('index.html')
text = path.read_text(encoding='utf-8')

old_lock = 'body.pc-detail-lock{overflow:hidden;}'
assert old_lock in text
text = text.replace(old_lock, 'body.folio-detail-lock{overflow:hidden;}', 1)

css_start = text.index('.sub-projects-wrap{')
css_end = text.index('.skills-grid{', css_start)
new_css = r'''.folio-section{
  --folio-bg:#0a0b0b;--folio-ink:#dfe7e2;--folio-muted:#7a8979;--folio-line:rgba(223,231,226,.17);--folio-accent:var(--accent);
  height:610vh;padding:0;background:var(--folio-bg);color:var(--folio-ink);position:relative;isolation:isolate;overflow:visible;
}
:root[data-theme="light"] .folio-section{background:var(--folio-bg);color:var(--folio-ink);}
.folio-section::after{display:none !important;}
.folio-sticky{position:sticky;top:0;height:100svh;min-height:620px;overflow:hidden;}
.folio-shell{position:relative;height:100%;padding:clamp(24px,3.2vw,48px) clamp(22px,4vw,64px) clamp(24px,3vw,44px);display:grid;grid-template-rows:auto minmax(0,1fr) auto;}
.folio-topline{display:grid;grid-template-columns:auto minmax(110px,280px) auto;align-items:center;gap:22px;z-index:4;font-family:var(--font-mono);font-size:10px;line-height:1;text-transform:uppercase;letter-spacing:.12em;color:var(--folio-muted);}
.folio-label{font:inherit;color:var(--folio-ink);margin:0;white-space:nowrap;}
.folio-progress{position:relative;height:1px;background:rgba(223,231,226,.16);overflow:hidden;}
.folio-progress-fill{position:absolute;inset:0;transform-origin:left center;transform:scaleX(0);background:var(--folio-accent);will-change:transform;}
.folio-instruction{text-align:right;white-space:nowrap;}
.folio-stage{position:relative;display:flex;align-items:center;justify-content:center;min-height:0;z-index:2;}
.folio-ribbon{position:relative;width:min(94vw,1220px);height:min(58vh,590px);perspective:1300px;transform-style:preserve-3d;touch-action:pan-y;user-select:none;}
.folio-ribbon.is-dragging{cursor:grabbing;}
.folio-project{position:absolute;left:50%;top:50%;width:clamp(72px,7.6vw,110px);height:min(56vh,560px);padding:0;margin:0;border:0;background:transparent;color:inherit;font:inherit;text-align:left;cursor:pointer;will-change:transform,opacity;transform-style:preserve-3d;transform-origin:center;}
.folio-project-inner{position:absolute;inset:0;overflow:hidden;border:1px solid var(--folio-line);background:#111;transition:border-color .25s ease,box-shadow .35s ease,filter .35s ease;}
.folio-project::before{content:"";position:absolute;inset:-8px;z-index:-1;background:var(--card-accent,var(--folio-accent));opacity:0;filter:blur(24px);transition:opacity .35s ease;}
.folio-project:hover::before,.folio-project.is-active::before{opacity:.12;}
.folio-project:hover .folio-project-inner,.folio-project.is-active .folio-project-inner{border-color:color-mix(in srgb,var(--card-accent,var(--folio-accent)) 58%,transparent);}
.folio-project:focus-visible{outline:1px solid var(--card-accent,var(--folio-accent));outline-offset:6px;border-radius:0;}
.folio-project img,.folio-cover-fallback{display:block;width:100%;height:100%;object-fit:cover;}
.folio-project img{filter:grayscale(1) saturate(.1) brightness(.52) contrast(1.08);transition:filter .4s var(--ease),transform .8s var(--ease);}
.folio-project:hover img,.folio-project.is-active img{filter:grayscale(0) saturate(.95) brightness(.9) contrast(1.03);transform:scale(1.035);}
.folio-cover-fallback{position:relative;overflow:hidden;background:var(--cover-bg,#111);color:var(--cover-ink,#eee);filter:grayscale(.92) saturate(.18) brightness(.62);transition:filter .4s var(--ease),transform .8s var(--ease);}
.folio-cover-fallback::before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,transparent 49.5%,color-mix(in srgb,var(--cover-accent,#fff) 22%,transparent) 50%,transparent 50.5%),repeating-linear-gradient(0deg,transparent 0 34px,color-mix(in srgb,var(--cover-ink,#fff) 9%,transparent) 35px 36px);opacity:.7;}
.folio-cover-fallback::after{content:"";position:absolute;width:120%;aspect-ratio:1;border:1px solid var(--cover-accent,#fff);border-radius:50%;left:-52%;top:18%;opacity:.18;}
.folio-project:hover .folio-cover-fallback,.folio-project.is-active .folio-cover-fallback{filter:grayscale(0) saturate(1) brightness(.95);transform:scale(1.02);}
.folio-cover-abbr{position:absolute;left:50%;top:50%;z-index:2;writing-mode:vertical-rl;transform:translate(-50%,-50%) rotate(180deg);font-family:var(--font-display);font-size:clamp(34px,5.1vw,72px);font-weight:700;line-height:.78;letter-spacing:-.08em;text-transform:uppercase;}
.folio-project-index{position:absolute;top:10px;left:10px;z-index:3;font-family:var(--font-mono);font-size:9px;letter-spacing:.08em;color:#fff;mix-blend-mode:difference;opacity:.78;}
.folio-mobile-label{display:none;}
.folio-caption{position:relative;z-index:4;display:grid;grid-template-columns:minmax(0,1fr) minmax(310px,.62fr);align-items:end;gap:44px;min-height:150px;border-top:1px solid var(--folio-line);padding-top:18px;}
.folio-caption-main{min-width:0;}
.folio-caption-index{font-family:var(--font-mono);font-size:10px;letter-spacing:.12em;color:var(--folio-accent);margin-bottom:8px;}
.folio-caption-title{margin:0;font-family:var(--font-display);font-size:clamp(42px,6.8vw,102px);font-weight:600;line-height:.84;letter-spacing:-.055em;color:var(--folio-ink);max-width:12ch;text-wrap:balance;}
.folio-caption-side{display:grid;gap:18px;align-self:end;padding-bottom:4px;}
.folio-caption-meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;}
.folio-meta-block span{display:block;}.folio-meta-key{font-family:var(--font-mono);font-size:8.5px;letter-spacing:.14em;color:var(--folio-muted);margin-bottom:5px;}.folio-meta-value{font-family:var(--font-mono);font-size:10px;line-height:1.35;color:var(--folio-ink);text-transform:uppercase;}
.folio-actions{display:flex;align-items:center;justify-content:space-between;gap:12px;}
.folio-open{background:none;border:0;border-bottom:1px solid currentColor;color:var(--folio-ink);padding:0 0 4px;cursor:pointer;font-family:var(--font-mono);font-size:10px;letter-spacing:.12em;text-transform:uppercase;transition:color .2s ease,border-color .2s ease;}.folio-open:hover{color:var(--folio-accent);border-color:var(--folio-accent);}
.folio-nav{display:flex;align-items:center;gap:7px;}.folio-nav button{width:32px;height:32px;border:1px solid var(--folio-line);border-radius:50%;background:none;color:var(--folio-ink);cursor:pointer;font-family:var(--font-mono);font-size:13px;line-height:1;transition:border-color .2s ease,color .2s ease,transform .2s ease;}.folio-nav button:hover{border-color:var(--folio-accent);color:var(--folio-accent);transform:scale(1.04);}
.folio-detail{position:fixed;inset:0;z-index:320;background:var(--folio-detail-bg,#0a0b0b);color:var(--folio-detail-ink,#e7edf5);visibility:hidden;pointer-events:none;clip-path:inset(100% 0 0 0);-webkit-clip-path:inset(100% 0 0 0);transition:clip-path .72s var(--ease),-webkit-clip-path .72s var(--ease),visibility 0s linear .72s;}
.folio-detail[hidden]{display:none !important;}.folio-detail.is-open{visibility:visible;pointer-events:auto;clip-path:inset(0);-webkit-clip-path:inset(0);transition:clip-path .72s var(--ease),-webkit-clip-path .72s var(--ease);}
.folio-detail-scroll{height:100%;overflow-y:auto;overscroll-behavior:contain;scrollbar-width:thin;}
.folio-detail-bar{position:sticky;top:0;z-index:10;display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:22px;padding:18px clamp(20px,3vw,44px);border-bottom:1px solid color-mix(in srgb,currentColor 16%,transparent);background:color-mix(in srgb,var(--folio-detail-bg,#0a0b0b) 88%,transparent);backdrop-filter:blur(14px);font-family:var(--font-mono);font-size:9.5px;letter-spacing:.12em;text-transform:uppercase;}
.folio-detail-close{background:none;border:0;border-bottom:1px solid currentColor;color:inherit;padding:0 0 3px;cursor:pointer;font:inherit;letter-spacing:.12em;text-transform:uppercase;}.folio-detail-close:hover{color:var(--folio-detail-accent,var(--accent));}
.folio-detail-hero{position:relative;min-height:68svh;padding:clamp(42px,7vw,96px) clamp(22px,5vw,76px) 46px;display:flex;flex-direction:column;justify-content:flex-end;overflow:hidden;border-bottom:1px solid color-mix(in srgb,currentColor 16%,transparent);}
.folio-detail-number{position:absolute;right:-.025em;top:.08em;font-family:var(--font-display);font-weight:700;font-size:clamp(150px,30vw,520px);line-height:.7;letter-spacing:-.09em;opacity:.055;pointer-events:none;user-select:none;}
.folio-detail-kicker{font-family:var(--font-mono);font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:var(--folio-detail-accent,var(--accent));margin:0 0 16px;}
.folio-detail-title{position:relative;z-index:1;font-family:var(--font-display);font-size:clamp(54px,10.8vw,170px);font-weight:600;line-height:.82;letter-spacing:-.065em;max-width:10ch;margin:0;text-wrap:balance;}
.folio-detail-summary{position:relative;z-index:1;max-width:620px;margin:28px 0 0;font-size:14px;line-height:1.65;opacity:.72;}
.folio-detail-meta{position:relative;z-index:1;margin-top:38px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1px;border-top:1px solid color-mix(in srgb,currentColor 18%,transparent);border-left:1px solid color-mix(in srgb,currentColor 18%,transparent);}
.folio-detail-meta-item{padding:14px 14px 16px;border-right:1px solid color-mix(in srgb,currentColor 18%,transparent);border-bottom:1px solid color-mix(in srgb,currentColor 18%,transparent);min-width:0;}.folio-detail-meta-key{display:block;font-family:var(--font-mono);font-size:8px;letter-spacing:.14em;text-transform:uppercase;opacity:.48;margin-bottom:7px;}.folio-detail-meta-value{display:block;font-family:var(--font-mono);font-size:10px;line-height:1.4;text-transform:uppercase;overflow-wrap:anywhere;}
.folio-detail-media{min-height:62vh;padding:clamp(22px,5vw,72px);display:flex;align-items:center;justify-content:center;background:#080a0c;color:#e7edf5;}.folio-detail-media .scene-media{width:min(100%,1240px);}.folio-detail-media .scene-media>img{display:block;width:100%;height:auto;max-height:76vh;object-fit:contain;}.folio-detail-media .chart-panel,.folio-detail-media .term-panel{margin:0;border-radius:0;width:100%;}.folio-detail-media .live-embed{width:100%;height:min(72vh,720px);border-radius:0;margin:0;display:flex;flex-direction:column;}.folio-detail-media .live-embed iframe{flex:1;height:auto !important;min-height:0;}
.folio-detail-copy{padding:clamp(46px,7vw,96px) clamp(22px,7vw,110px);}.folio-detail-copy .scene-detail-copy{max-width:980px;margin:0 auto;}.folio-detail-copy .feature-desc{max-width:760px;font-size:clamp(16px,1.7vw,21px);line-height:1.72;color:inherit;opacity:.78;margin-bottom:30px;}.folio-detail-copy .feature-stats{margin:24px 0;}.folio-detail-copy .chip{color:inherit;border-color:color-mix(in srgb,currentColor 30%,transparent);opacity:.86;}.folio-detail-copy .why summary,.folio-detail-copy .feature-links a{color:var(--folio-detail-accent,var(--accent));}.folio-detail-copy .why-body{color:inherit;opacity:.72;background:transparent;border-left-color:var(--folio-detail-accent,var(--accent));}.folio-detail-copy .feature-flow .flow-node{color:inherit;border-color:color-mix(in srgb,currentColor 30%,transparent);background:transparent;}.folio-detail-copy .feature-flow .flow-node.accent{color:var(--folio-detail-accent,var(--accent));border-color:var(--folio-detail-accent,var(--accent));background:transparent;}
.folio-detail-footer{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:18px;padding:28px clamp(22px,5vw,76px) 38px;border-top:1px solid color-mix(in srgb,currentColor 16%,transparent);font-family:var(--font-mono);font-size:10px;text-transform:uppercase;letter-spacing:.1em;}.folio-detail-footer button{background:none;border:0;color:inherit;font:inherit;text-transform:inherit;letter-spacing:inherit;cursor:pointer;padding:8px 0;}.folio-detail-footer button:first-child{text-align:left;}.folio-detail-footer button:last-child{text-align:right;}.folio-detail-footer button:hover{color:var(--folio-detail-accent,var(--accent));}.folio-detail-position{opacity:.5;}
@media(max-height:720px) and (min-width:821px){.folio-sticky{min-height:560px}.folio-ribbon{height:52vh}.folio-project{height:50vh}.folio-caption{min-height:126px}.folio-caption-title{font-size:clamp(38px,5.8vw,78px)}}
@media(max-width:820px){
 .folio-section{height:auto;padding:82px 0 92px;overflow:hidden}.folio-sticky{position:relative;top:auto;height:auto;min-height:0;overflow:visible}.folio-shell{height:auto;display:block;padding:0 18px}.folio-topline{grid-template-columns:auto 1fr;margin-bottom:34px}.folio-progress{display:none}.folio-instruction{text-align:right;font-size:9px}.folio-stage{display:block}.folio-ribbon{position:static;width:100%;height:auto;display:grid;grid-template-columns:1fr;gap:18px;perspective:none;touch-action:auto}.folio-project{position:relative;left:auto;top:auto;width:100%;height:auto;aspect-ratio:4/3;transform:none !important;opacity:1 !important;will-change:auto}.folio-project-inner{position:absolute;inset:0}.folio-project::before{display:none}.folio-project img{filter:grayscale(.9) saturate(.2) brightness(.62)}.folio-project.is-mobile-active img,.folio-project:hover img{filter:grayscale(0) saturate(1) brightness(.92)}.folio-cover-fallback{filter:grayscale(.8) saturate(.28) brightness(.72)}.folio-project.is-mobile-active .folio-cover-fallback,.folio-project:hover .folio-cover-fallback{filter:grayscale(0) saturate(1) brightness(.96)}.folio-cover-abbr{writing-mode:horizontal-tb;transform:translate(-50%,-50%);font-size:clamp(70px,25vw,132px)}.folio-project-index{top:14px;left:14px;font-size:10px}.folio-mobile-label{position:absolute;left:0;right:0;bottom:0;z-index:4;display:grid;grid-template-columns:1fr auto;align-items:end;gap:13px;padding:42px 14px 14px;background:linear-gradient(transparent,rgba(0,0,0,.82));color:#f2f5f3}.folio-mobile-label strong{display:block;font-family:var(--font-display);font-size:clamp(22px,7vw,34px);line-height:.92;letter-spacing:-.035em}.folio-mobile-label small{display:block;margin-top:6px;font-family:var(--font-mono);font-size:8.5px;line-height:1.3;letter-spacing:.08em;text-transform:uppercase;opacity:.72}.folio-mobile-arrow{font-family:var(--font-mono);font-size:17px;color:var(--card-accent,var(--accent))}.folio-caption{display:none}.folio-detail-bar{grid-template-columns:1fr auto;padding:15px 18px}.folio-detail-bar>span:nth-child(2){display:none}.folio-detail-hero{min-height:60svh;padding:42px 18px 30px}.folio-detail-number{font-size:42vw;top:.14em}.folio-detail-title{font-size:clamp(48px,16vw,82px);max-width:8ch}.folio-detail-summary{font-size:13px;line-height:1.6;margin-top:22px}.folio-detail-meta{grid-template-columns:1fr 1fr;margin-top:28px}.folio-detail-media{min-height:0;padding:18px}.folio-detail-media .live-embed{height:54vh}.folio-detail-copy{padding:42px 18px 56px}.folio-detail-copy .feature-desc{font-size:16px}.folio-detail-footer{padding:20px 18px 28px;font-size:9px}
}
@media(prefers-reduced-motion:reduce){.folio-section{height:auto;padding:82px 0}.folio-sticky{position:relative;height:auto;min-height:0;overflow:visible}.folio-shell{height:auto;display:block}.folio-topline{margin-bottom:30px}.folio-progress{display:none}.folio-ribbon{position:static;width:100%;height:auto;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;perspective:none}.folio-project{position:relative;left:auto;top:auto;width:100%;height:auto;aspect-ratio:3/4;transform:none !important;opacity:1 !important;will-change:auto}.folio-project-inner{position:absolute;inset:0}.folio-caption{display:none}.folio-mobile-label{display:grid;position:absolute;left:0;right:0;bottom:0;z-index:4;grid-template-columns:1fr auto;gap:12px;padding:40px 12px 12px;background:linear-gradient(transparent,rgba(0,0,0,.82));color:#fff}.folio-mobile-label strong{font-family:var(--font-display);font-size:24px;line-height:.95}.folio-mobile-label small{display:block;font-family:var(--font-mono);font-size:8px;margin-top:5px;opacity:.7}.folio-detail{transition:opacity .15s ease;clip-path:none !important;-webkit-clip-path:none !important;opacity:0}.folio-detail.is-open{opacity:1}}
@media(prefers-reduced-motion:reduce) and (max-width:620px){.folio-ribbon{grid-template-columns:1fr}.folio-project{aspect-ratio:4/3}}
'''
text = text[:css_start] + new_css + '\n\n' + text[css_end:]

markup_start = text.index('<section id="projects" class="projects-wall reveal">')
source_start = text.index('  <div id="pwSource" hidden>', markup_start)
projects = [
    ('craft','Interactive Diploma','Creative / 3D','Three.js','Fully interactive','ID','#0c0906','#f4ecdf','#f0b429',None,"A full 3D, physically-lit recreation of my actual diploma. It's live. Drag it."),
    ('proj-siem','Log Correlator SIEM','Security tool','Python','25 tests passing','SIEM','#081413','#eafffb','#5eead4','screenshots/log-correlator-siem.webp','Correlates sequences of events across two log sources into one incident, not two alerts.'),
    ('proj-helpdesk','Helpdesk Ticket Analytics','Analytics tool','Python','14 tests passing','HD','#e9edf1','#141b24','#285f8f',None,'Turns a raw ticket export into SLA compliance, resolution-time, and volume metrics.'),
    ('proj-ad-auditor','AD Security Auditor','Security tool','PowerShell','Pester tested','AD','#0d0b14','#efeaff','#9d84e8','screenshots/ad-security-auditor.webp','Audits Active Directory security posture entirely offline, from exported CSV data.'),
    ('proj-phishing','Phishing Email Analyzer','Security tool','Python','46 tests passing','PH','#160a0d','#ffe9ee','#e8748c','screenshots/phishing-email-analyzer.webp','Statically analyzes raw .eml files for phishing indicators, fully offline.'),
    ('proj-jotrelay','JotRelay','Web app','JS / Supabase','Live demo','JR','#eef7f1','#0c1f15','#256f4a',None,'Real-time encrypted collaborative notepad with shareable links and an installable PWA.'),
    ('proj-toolkit','AD & Endpoint Automation Toolkit','Automation','PowerShell','PS 5.1 compatible','EP','#170f08','#ffe9d1','#e2a35c',None,'Provisioning, offboarding, and compliance scripts. Every write action supports -WhatIf.'),
    ('proj-winlog','WinLog Threat Hunter','Threat hunting','Python','25 tests passing','WL','#071316','#eafbff','#5fc9d8',None,'Parses Windows Security/Sysmon events and maps findings to MITRE ATT&CK techniques.')
]

def esc(s):
    return s.replace('&','&amp;').replace('"','&quot;').replace('<','&lt;').replace('>','&gt;')

cards=[]
for i,(pid,title,ptype,stack,status,abbr,bg,ink,accent,thumb,hint) in enumerate(projects):
    media = f'<img src="{thumb}" alt="" loading="lazy">' if thumb else f'<span class="folio-cover-fallback" style="--cover-bg:{bg};--cover-ink:{ink};--cover-accent:{accent};"><span class="folio-cover-abbr">{esc(abbr)}</span></span>'
    cards.append(f'''          <button class="folio-project" id="{pid}" type="button" data-index="{i}" data-title="{esc(title)}" data-type="{esc(ptype)}" data-stack="{esc(stack)}" data-status="{esc(status)}" data-abbr="{esc(abbr)}" data-bg="{bg}" data-ink="{ink}" data-accent="{accent}"{f' data-thumb="{thumb}"' if thumb else ''} data-hint="{esc(hint)}" style="--card-accent:{accent};">
            <span class="folio-project-inner">{media}<span class="folio-project-index">{i+1:02d}</span><span class="folio-mobile-label"><span><strong>{esc(title)}</strong><small>{esc(ptype)} · {esc(stack)}</small></span><span class="folio-mobile-arrow">↗</span></span></span>
          </button>''')

new_markup = '''<section id="projects" class="folio-section" style="--folio-count:8">
  <div class="folio-sticky">
    <div class="folio-shell">
      <div class="folio-topline"><h2 class="folio-label">Selected work</h2><div class="folio-progress" aria-hidden="true"><span class="folio-progress-fill" id="folioProgressFill"></span></div><span class="folio-instruction">Scroll / drag / arrows</span></div>
      <div class="folio-stage"><div class="folio-ribbon" id="folioRibbon" aria-label="Project gallery">
''' + '\n'.join(cards) + '''
        </div></div>
      <div class="folio-caption">
        <div class="folio-caption-main"><div class="folio-caption-index" id="folioCaptionIndex">01 / 08</div><h3 class="folio-caption-title" id="folioCaptionTitle">Interactive Diploma</h3></div>
        <div class="folio-caption-side"><div class="folio-caption-meta"><div class="folio-meta-block"><span class="folio-meta-key">A / Type</span><span class="folio-meta-value" id="folioMetaType">Creative / 3D</span></div><div class="folio-meta-block"><span class="folio-meta-key">B / Stack</span><span class="folio-meta-value" id="folioMetaStack">Three.js</span></div><div class="folio-meta-block"><span class="folio-meta-key">C / Status</span><span class="folio-meta-value" id="folioMetaStatus">Fully interactive</span></div></div><div class="folio-actions"><button class="folio-open" id="folioOpen" type="button">Explore project ↗</button><div class="folio-nav" aria-label="Project navigation"><button id="folioPrev" type="button" aria-label="Previous project">←</button><button id="folioNext" type="button" aria-label="Next project">→</button></div></div></div>
      </div>
    </div>
  </div>
</section>
<div class="folio-detail" id="folioDetail" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="folioDetailTitle" hidden>
  <div class="folio-detail-scroll" id="folioDetailScroll">
    <div class="folio-detail-bar"><span>Selected work</span><span id="folioDetailTopPos">01 / 08</span><button class="folio-detail-close" id="folioDetailClose" type="button">Close ×</button></div>
    <div class="folio-detail-hero"><span class="folio-detail-number" id="folioDetailNumber" aria-hidden="true">01</span><p class="folio-detail-kicker" id="folioDetailKicker">Creative / 3D · Three.js</p><h3 class="folio-detail-title" id="folioDetailTitle">Interactive Diploma</h3><p class="folio-detail-summary" id="folioDetailSummary"></p><div class="folio-detail-meta"><div class="folio-detail-meta-item"><span class="folio-detail-meta-key">A / Type</span><span class="folio-detail-meta-value" id="folioDetailType"></span></div><div class="folio-detail-meta-item"><span class="folio-detail-meta-key">B / Stack</span><span class="folio-detail-meta-value" id="folioDetailStack"></span></div><div class="folio-detail-meta-item"><span class="folio-detail-meta-key">C / Status</span><span class="folio-detail-meta-value" id="folioDetailStatus"></span></div><div class="folio-detail-meta-item"><span class="folio-detail-meta-key">D / Index</span><span class="folio-detail-meta-value" id="folioDetailIndex"></span></div></div></div>
    <div class="folio-detail-media" id="folioDetailMedia"></div><div class="folio-detail-copy" id="folioDetailCopy"></div>
    <div class="folio-detail-footer"><button id="folioDetailPrev" type="button">← Previous</button><span class="folio-detail-position" id="folioDetailPos">01 / 08</span><button id="folioDetailNext" type="button">Next →</button></div>
  </div>
</div>

'''
text = text[:markup_start] + new_markup + text[source_start:]
text = text.replace('  <div id="pwSource" hidden>', '  <div id="folioSource" hidden>', 1)

js_start = text.index("(function(){\n  var root = document.querySelector('.projects-wall');")
js_end = text.index("(function(){\n  var canvas = document.getElementById('aboutCanvas');", js_start)
new_js = r'''(function(){
  var root=document.querySelector('.folio-section'),ribbon=document.getElementById('folioRibbon'),detail=document.getElementById('folioDetail'),sourceWrap=document.getElementById('folioSource');
  if(!root||!ribbon||!detail||!sourceWrap)return;
  var reduce=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches,mobileMQ=window.matchMedia?window.matchMedia('(max-width:820px)'):{matches:false},cards=Array.prototype.slice.call(ribbon.querySelectorAll('.folio-project')),N=cards.length;if(!N)return;
  function pad(n){return String(n).padStart(2,'0');}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}function staticLayout(){return reduce||mobileMQ.matches;}
  var PROJECTS=cards.map(function(card,i){var source=sourceWrap.querySelector('.proj-source[data-project="'+card.id+'"]');return{id:card.id,index:i,card:card,source:source,media:source?source.querySelector('.scene-media'):null,copy:source?source.querySelector('.scene-detail-copy'):null,title:card.dataset.title||card.id,type:card.dataset.type||'',stack:card.dataset.stack||'',status:card.dataset.status||'',bg:card.dataset.bg||'#0a0b0b',ink:card.dataset.ink||'#e7edf5',accent:card.dataset.accent||'#5eead4',hint:card.dataset.hint||''};});
  function indexForId(id){for(var i=0;i<N;i++){if(PROJECTS[i].id===id)return i;}return-1;}
  var progressFill=document.getElementById('folioProgressFill'),captionIndex=document.getElementById('folioCaptionIndex'),captionTitle=document.getElementById('folioCaptionTitle'),metaType=document.getElementById('folioMetaType'),metaStack=document.getElementById('folioMetaStack'),metaStatus=document.getElementById('folioMetaStatus'),openBtn=document.getElementById('folioOpen'),prevBtn=document.getElementById('folioPrev'),nextBtn=document.getElementById('folioNext');
  var currentPosition=0,targetPosition=0,activeIndex=0,renderRAF=null,inSection=false;
  function setActive(index){index=clamp(index,0,N-1);activeIndex=index;var p=PROJECTS[index];root.style.setProperty('--folio-accent',p.accent);cards.forEach(function(card,i){var active=i===index;card.classList.toggle('is-active',active);if(active)card.setAttribute('aria-current','true');else card.removeAttribute('aria-current');});if(captionIndex)captionIndex.textContent=pad(index+1)+' / '+pad(N);if(captionTitle)captionTitle.textContent=p.title;if(metaType)metaType.textContent=p.type;if(metaStack)metaStack.textContent=p.stack;if(metaStatus)metaStatus.textContent=p.status;}
  function render(position){if(staticLayout())return;var spacing=clamp(window.innerWidth*.086,88,126);cards.forEach(function(card,i){var d=i-position,ad=Math.abs(d),x=d*spacing,y=Math.min(118,ad*ad*6.5),z=-Math.min(430,ad*96),ry=clamp(d*-12.5,-64,64),scale=1-Math.min(.29,ad*.052),opacity=clamp(1-ad*.085,.22,1);card.style.transform='translate(-50%,-50%) translate3d('+x.toFixed(2)+'px,'+y.toFixed(2)+'px,'+z.toFixed(2)+'px) rotateY('+ry.toFixed(2)+'deg) scale('+scale.toFixed(3)+')';card.style.opacity=opacity.toFixed(3);card.style.zIndex=String(100-Math.round(ad*10));});if(progressFill){var pp=N>1?clamp(position/(N-1),0,1):1;progressFill.style.transform='scaleX('+pp.toFixed(4)+')';}setActive(clamp(Math.round(position),0,N-1));}
  function animateRender(){renderRAF=null;if(staticLayout())return;currentPosition+=(targetPosition-currentPosition)*.16;if(Math.abs(targetPosition-currentPosition)<.001)currentPosition=targetPosition;render(currentPosition);if(currentPosition!==targetPosition)renderRAF=requestAnimationFrame(animateRender);}function wakeRender(){if(!renderRAF&&!staticLayout())renderRAF=requestAnimationFrame(animateRender);}
  function syncFromScroll(){if(staticLayout())return;var rect=root.getBoundingClientRect(),span=Math.max(1,root.offsetHeight-window.innerHeight);targetPosition=clamp((-rect.top)/span,0,1)*(N-1);inSection=rect.top<=window.innerHeight*.22&&rect.bottom>=window.innerHeight*.78;wakeRender();}
  function sectionTop(){return window.scrollY+root.getBoundingClientRect().top;}
  function scrollToIndex(index,instant){index=clamp(index,0,N-1);if(staticLayout()){var c=cards[index];if(c)c.scrollIntoView({behavior:instant||reduce?'auto':'smooth',block:'center'});return;}var span=Math.max(1,root.offsetHeight-window.innerHeight),y=sectionTop()+(N>1?span*(index/(N-1)):0);targetPosition=index;wakeRender();if(window.hsLenis){try{window.hsLenis.scrollTo(y,instant?{immediate:true}:{duration:.9});return;}catch(e){}}window.scrollTo({top:y,behavior:instant||reduce?'auto':'smooth'});}
  if(!staticLayout()){if(window.hsLenis&&typeof window.hsLenis.on==='function')window.hsLenis.on('scroll',syncFromScroll);else window.addEventListener('scroll',syncFromScroll,{passive:true});window.addEventListener('resize',syncFromScroll);syncFromScroll();currentPosition=targetPosition;render(currentPosition);}else{cards.forEach(function(c){c.style.transform='';c.style.opacity='';c.style.zIndex='';});setActive(0);if('IntersectionObserver'in window){var mobileIO=new IntersectionObserver(function(entries){entries.forEach(function(en){en.target.classList.toggle('is-mobile-active',en.isIntersecting);});},{threshold:.48});cards.forEach(function(c){mobileIO.observe(c);});}}
  var dragStartX=0,dragging=false,suppressClickUntil=0;ribbon.addEventListener('pointerdown',function(e){if(staticLayout()||(e.pointerType==='mouse'&&e.button!==0))return;dragStartX=e.clientX;dragging=true;ribbon.classList.add('is-dragging');try{ribbon.setPointerCapture(e.pointerId);}catch(err){}});ribbon.addEventListener('pointerup',function(e){if(!dragging)return;dragging=false;ribbon.classList.remove('is-dragging');var dx=e.clientX-dragStartX;if(Math.abs(dx)>42){suppressClickUntil=Date.now()+350;scrollToIndex(activeIndex+(dx<0?1:-1));}});ribbon.addEventListener('pointercancel',function(){dragging=false;ribbon.classList.remove('is-dragging');});
  var detailScroll=document.getElementById('folioDetailScroll'),detailClose=document.getElementById('folioDetailClose'),detailTopPos=document.getElementById('folioDetailTopPos'),detailNumber=document.getElementById('folioDetailNumber'),detailKicker=document.getElementById('folioDetailKicker'),detailTitle=document.getElementById('folioDetailTitle'),detailSummary=document.getElementById('folioDetailSummary'),detailType=document.getElementById('folioDetailType'),detailStack=document.getElementById('folioDetailStack'),detailStatus=document.getElementById('folioDetailStatus'),detailIndex=document.getElementById('folioDetailIndex'),detailMedia=document.getElementById('folioDetailMedia'),detailCopy=document.getElementById('folioDetailCopy'),detailPos=document.getElementById('folioDetailPos'),detailPrev=document.getElementById('folioDetailPrev'),detailNext=document.getElementById('folioDetailNext');var detailIndexActive=-1,detailGen=0;
  function setHash(id,mode){if(mode===false)return;try{if(mode==='replace')history.replaceState(null,'','#'+id);else history.pushState(null,'','#'+id);}catch(e){}}
  function returnDetailContent(){if(detailIndexActive===-1)return;var p=PROJECTS[detailIndexActive];if(!p.source)return;if(p.media&&p.media.parentNode===detailMedia)p.source.insertBefore(p.media,p.source.firstChild);if(p.copy&&p.copy.parentNode===detailCopy)p.source.appendChild(p.copy);}
  function populateDetail(index){returnDetailContent();var p=PROJECTS[index];detailIndexActive=index;detail.style.setProperty('--folio-detail-bg',p.bg);detail.style.setProperty('--folio-detail-ink',p.ink);detail.style.setProperty('--folio-detail-accent',p.accent);if(detailTopPos)detailTopPos.textContent=pad(index+1)+' / '+pad(N);if(detailNumber)detailNumber.textContent=pad(index+1);if(detailKicker)detailKicker.textContent=p.type+' · '+p.stack;if(detailTitle)detailTitle.textContent=p.title;if(detailSummary)detailSummary.textContent=p.hint;if(detailType)detailType.textContent=p.type;if(detailStack)detailStack.textContent=p.stack;if(detailStatus)detailStatus.textContent=p.status;if(detailIndex)detailIndex.textContent=pad(index+1)+' / '+pad(N);if(detailPos)detailPos.textContent=pad(index+1)+' / '+pad(N);if(p.media)detailMedia.appendChild(p.media);if(p.copy)detailCopy.appendChild(p.copy);if(detailScroll)detailScroll.scrollTop=0;}
  function openDetail(index,opts){opts=opts||{};index=((index%N)+N)%N;detailGen++;setActive(index);populateDetail(index);if(detail.hidden){detail.hidden=false;detail.setAttribute('aria-hidden','false');if(opts.instant||reduce)detail.style.transition='none';void detail.offsetWidth;detail.classList.add('is-open');if(opts.instant||reduce)requestAnimationFrame(function(){requestAnimationFrame(function(){detail.style.transition='';});});}document.body.classList.add('folio-detail-lock');if(window.hsLenis)window.hsLenis.stop();setHash(PROJECTS[index].id,opts.updateHash);if(!opts.noFocus&&detailClose)detailClose.focus();}
  function closeDetail(opts){opts=opts||{};if(detail.hidden)return;detailGen++;var myGen=detailGen,focusCard=detailIndexActive!==-1?PROJECTS[detailIndexActive].card:null;detail.classList.remove('is-open');detail.setAttribute('aria-hidden','true');document.body.classList.remove('folio-detail-lock');if(window.hsLenis)window.hsLenis.start();function finish(){if(myGen!==detailGen)return;detail.hidden=true;returnDetailContent();detailIndexActive=-1;}if(reduce)finish();else{var ended=false;detail.addEventListener('transitionend',function te(e){if(e.target!==detail)return;detail.removeEventListener('transitionend',te);ended=true;finish();});setTimeout(function(){if(!ended)finish();},820);}setHash('projects',opts.updateHash);if(focusCard&&!opts.noFocus)focusCard.focus();}
  function nextDetail(){openDetail((detailIndexActive===-1?activeIndex:detailIndexActive)+1,{updateHash:'replace',noFocus:true});}function prevDetail(){openDetail((detailIndexActive===-1?activeIndex:detailIndexActive)-1,{updateHash:'replace',noFocus:true});}
  cards.forEach(function(card,i){card.addEventListener('click',function(){if(Date.now()<suppressClickUntil)return;if(!staticLayout()){targetPosition=i;currentPosition=i;render(i);}openDetail(i);});});if(openBtn)openBtn.addEventListener('click',function(){openDetail(activeIndex);});if(prevBtn)prevBtn.addEventListener('click',function(){scrollToIndex(activeIndex-1);});if(nextBtn)nextBtn.addEventListener('click',function(){scrollToIndex(activeIndex+1);});if(detailClose)detailClose.addEventListener('click',function(){closeDetail();});if(detailPrev)detailPrev.addEventListener('click',prevDetail);if(detailNext)detailNext.addEventListener('click',nextDetail);
  detail.addEventListener('keydown',function(e){if(e.key!=='Tab')return;var focusables=detail.querySelectorAll('a[href],button:not([disabled]),[tabindex]:not([tabindex="-1"])');if(!focusables.length)return;var first=focusables[0],last=focusables[focusables.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
  var swipeStartX=0,swipeStartY=0,swipeActive=false;detail.addEventListener('pointerdown',function(e){if(e.pointerType==='mouse')return;if(e.target.closest&&(e.target.closest('iframe')||e.target.closest('.lf-overlay')||e.target.closest('a')||e.target.closest('button')))return;swipeStartX=e.clientX;swipeStartY=e.clientY;swipeActive=true;});detail.addEventListener('pointerup',function(e){if(!swipeActive)return;swipeActive=false;var dx=e.clientX-swipeStartX,dy=e.clientY-swipeStartY;if(Math.abs(dx)>64&&Math.abs(dx)>Math.abs(dy)*1.35){if(dx<0)nextDetail();else prevDetail();}});detail.addEventListener('pointercancel',function(){swipeActive=false;});
  function typingTarget(el){if(!el)return false;var tag=el.tagName;return tag==='INPUT'||tag==='TEXTAREA'||tag==='SELECT'||tag==='IFRAME'||el.isContentEditable;}
  document.addEventListener('keydown',function(e){if(typingTarget(document.activeElement)||document.body.classList.contains('menu-open'))return;if(!detail.hidden){if(e.key==='Escape')closeDetail();else if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();nextDetail();}else if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();prevDetail();}return;}if(!staticLayout()&&inSection){if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();scrollToIndex(activeIndex+1);}else if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();scrollToIndex(activeIndex-1);}}});
  window.addEventListener('hashchange',function(){var idx=indexForId(location.hash.slice(1));if(idx!==-1){if(!staticLayout())scrollToIndex(idx,true);openDetail(idx,{updateHash:false});}else if(detailIndexActive!==-1)closeDetail({updateHash:false});});
  window.hsScrollToProjSlide=function(el){if(!el)return false;var idx=el.id?indexForId(el.id):-1;if(idx===-1)return false;scrollToIndex(idx);setTimeout(function(){openDetail(idx);},reduce?0:420);return true;};window.hsProjects={goToProject:function(i){scrollToIndex(i);setTimeout(function(){openDetail(i);},reduce?0:420);},next:function(){if(detailIndexActive!==-1)nextDetail();else scrollToIndex(activeIndex+1);},prev:function(){if(detailIndexActive!==-1)prevDetail();else scrollToIndex(activeIndex-1);},closeProjectDetail:closeDetail};
  var initialIdx=indexForId((window.hsInitialHash||'').slice(1));if(initialIdx!==-1){scrollToIndex(initialIdx,true);openDetail(initialIdx,{instant:true,updateHash:'replace'});}
})();


'''
text = text[:js_start] + new_js + text[js_end:]

old_tilt = "var targets = document.querySelectorAll('.stat, .mini-card, .skill-group, .teaser-item');"
assert old_tilt in text
text = text.replace(old_tilt, "var targets = document.querySelectorAll('.stat, .skill-group, .teaser-item');", 1)
old_hover = "var hoverSel = 'a, button, .btn, .pw-row, .stat, .mini-card, .skill-group, .cert-proof, .tl-item';"
assert old_hover in text
text = text.replace(old_hover, "var hoverSel = 'a, button, .btn, .folio-project, .stat, .skill-group, .cert-proof, .tl-item';", 1)

path.write_text(text, encoding='utf-8')
